<a href="https://colab.research.google.com/github/gayathriramanesh/numpy_basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


prints the dimension of the array


In [3]:
a=np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


gives the byte size of an element

In [4]:
print(a.itemsize)

8


prints the data type of the array

In [5]:
print(a.dtype)

int64


size of the array

In [6]:
print(a.size)

6


prints the no of rows and columns

In [7]:
print(a.shape)

(2, 3)


changes the no of rows and columns

In [8]:
a=a.reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


prints the sliced value from index 0 and index 2

In [9]:
a=np.array([(1,2,3),(4,5,6)])
print(a[0:,2])
print(a[0:1,1])

[3 6]
[2]


linespacing-gives the no of values betwwen two nos

In [10]:
a=np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


sum,max n min of an array

In [11]:
a=np.array([(1,2,3),(4,5,6)])
print(a.max())
print(a.min())
print(a.sum())

6
1
21


axis-0 is column
axis-1 is row

In [12]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[5 7 9]
[ 6 15]


vertical and horizontal stacking

In [13]:
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(4,5,6)])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


addition and basic operations

In [14]:
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(4,5,6)])
print(a+b)

[[ 2  4  6]
 [ 8 10 12]]


to convert an np array into a single column

In [15]:
print(a.ravel())

[1 2 3 4 5 6]
